name: Rule engine continuous integration
on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#       - name: Use Node.js
#         uses: actions
#         with:
#           node-version: current
      - name: Install dependencies
        run: npm ci
      - name: Build Step
        run: npm run build --if-present
      - name: Run tests with coverage
        run: npm test
      - name: Check coverage
        run: |
          const coverage = require('./coverage/coverage-summary.json');
          const statements = coverage.total.statements.pct;
          const branches = coverage.total.branches.pct;
          const functions = coverage.total.functions.pct;
          const lines = coverage.total.lines.pct;
          const minCoverage = 90;
          const coverageThreshold = Math.min(statements, branches, functions, lines);
          if (coverageThreshold < minCoverage) {
            console.error(`Coverage below threshold: ${coverageThreshold}% < ${minCoverage}%`);
            process.exit(1);
          }
          
#       - name: Check Coverage
#         run: | 
#             coverage=$(jq -r '. total.lines' coverage/coverage-summary.json)
#             if(($(echo "$coverage < 100" | bc -l) )); then
#               echo "Coverage below 100%", $coverage%"
#               exit 1
#             else
#              echo "Hurray! Good Job With Test Coverage%"
#             fi
              
